name: MoveAsYou
version: '${project.version}'
description: ''
main: eng.pro.yui.mcpl.moveAsYou.MoveAsYou

author: Yui-KITAMURA

permissions:
  moveAsYou.token:
    description: トークンを発行する基本権限
    default: true
  moveAsYou.token.admin:
    description: 管理者向けトークンを有効にする拡張権限
    default: op
  moveAsYou.list:
    description: 自身のトークン一覧を表示する権限
    default: true
  moveAsYou.list.others:
    description: 他人のトークン一覧を表示する権限
    default: op
  moveAsYou.list.admin:
    description: 管理者向けトークンを含めて一覧表示する権限
    default: op
  moveAsYou.stats.admin:
    description: 管理者向け トークンの全体状況把握
    default: op

commands:
  MoveAsYou:
    description: MoveAsYouプラグインのコマンド
    aliases: [may, ma]
    subcommands:
      token:
        description: トークン発行
        usage: /MoveAsYou token [type]
      stats:
        description: トークンの発行状況
        usage: /MoveAsYou stats