name: update-versionTxt.yml

on:
  release: 
    types:
      - published

jobs:
  update-txt:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Write latest tag value
        run: |
          echo "${{ github.event.release.tag_name }}" > bukkit/version.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bukkit/version.txt
          git commit -m "Update version.txt for ${{ github.event.release.tag_name }}"
          git push
